export { default as Stats } from "./Stats";
export { default as Business } from "./Business";
export { default as Billing } from "./Billing";
export { default as CardDeal } from "./CardDeal";
export { default as Testimonials } from "./Testimonials";
export { default as Clients } from "./Clients";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
export { default as NavBar } from "./NavBar";
